START TRANSACTION;

CREATE TABLE "Comments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" integer NOT NULL,
    "Text" text NOT NULL,
    "Date" timestamp with time zone,
    "UserId" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id")
);

CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
);

CREATE TABLE "Tasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProjectId" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "DueDate" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "Priority" integer NOT NULL,
    "UserId" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id")
);

CREATE TABLE "Users"(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Role" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "ChangeLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "EntityName" VARCHAR(255) NOT NULL, 
    "PropertyName" VARCHAR(255) NOT NULL,
    "OriginalValue" TEXT,
    "NewValue" TEXT,
    "ModifiedAt" TIMESTAMP NOT NULL
);

INSERT INTO "Users" ("Username", "Role", "IsDeleted") VALUES ('Gerente', 'Manager', false);
INSERT INTO "Users" ("Username", "Role", "IsDeleted") VALUES ('Usuario', 'User', false);

COMMIT;

