# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  EclipeWorksTaskManager:
    build:
      context: "/Users/luizkolodziey/poc/TaskManager"
      dockerfile: "EclipeWorksTaskManager/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/EclipeWorksTaskManager.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "eclipeworkstaskmanager:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "/Users/luizkolodziey/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/luizkolodziey/poc/TaskManager/EclipeWorksTaskManager:/app:rw"
    - "/Users/luizkolodziey/poc/TaskManager:/src:rw"
    - "/Users/luizkolodziey/.local/share/JetBrains/RiderRemoteDebugger/2024.2.5/LinuxArm64:/opt/rider-debugger"
    - "/Users/luizkolodziey/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/luizkolodziey/Library/Logs/JetBrains/Rider2024.2/DebuggerWorker/JetBrains.Debugger.Worker.2024_9_24_18_33_14:/var/opt/rider-debugger:rw"
    working_dir: "/app"
